### ISSUE TITLE
Two and more connections

### ISSUE THREAD

**Issue by ZirgVoice** [d-exclaimation/pioneer-redis-pubsub#7]
In the browser I open 2 tabs with Apollo studio, start a subscription in the first tab and everything works fine, I go to the second tab and start a subscription there, the published data starts to come to the subscription from the second tab, at the same time stop coming to the subscription from the first tab. Ping pong continues to work in the first tab but without published data. When using `AsyncPubSub` instead of `RedisPubSub`, everything works fine.

**Comment by d-exclaimation** [comment]
I am surprised it worked for AsyncPubSub but not RedisPubSub as it seemed like the problem is that the broadcast failed to work here. Both PubSubs use the same Broadcast to distribute data to multiple subscriber the only different being where the data is coming from.

I tried replicating the issue with a server serving a subscription that listen to a channel and a mutation that just send a ping message to the same channel. I tried some scenarios, but I wasn't able to reproduce the issue:

1. Open Apollo Studio on a tab, start a subscription. Open Apollo Studio on another tab, start another subscription. Call the mutation from both the first and second tab. The data is received on both tab successfully

2. Open Apollo Studio on a tab, start a subscription. Call the mutation from the first tab repeatedly. The data is received on first tab successfully.  Open Apollo Studio on another tab, start another subscription. Data is also received on the second tab

3. Same as 2 but I close the subscription on the second tab, but keep pinging. Data is still received on the first tab

4. Same as 2 but I close the subscription on the first tab, but keep pinging. Data is also still received on the second tab

Can you provide me with more detail on this? Also this might have to do with the fact RediStack has recently moved their package repo into Github. There's an ongoing MR by someone else to fix this #6 (Sadly no update on this, if this become a bit more urgent. I'll fix the issue right away)

**Comment by ZirgVoice** [comment]
That's my mistake, I didn't store the `RedisPubSub` instance correctly.
